# Generated by Django 2.2.7 on 2020-03-26 16:03

import core_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('classNo', core_app.models.MyCharField(max_length=10, primary_key=True, serialize=False, verbose_name='班级编号')),
                ('className', models.CharField(max_length=30, verbose_name='班级名称')),
                ('institute', models.CharField(max_length=30, verbose_name='所属学院')),
                ('grade', models.SmallIntegerField(verbose_name='年级')),
                ('classNum', models.SmallIntegerField(verbose_name='班级人数')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('studentNo', core_app.models.MyCharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('studentName', models.CharField(max_length=30, verbose_name='姓名')),
                ('sex', core_app.models.MyCharField(max_length=2, verbose_name='性别')),
                ('birthday', models.DateTimeField(verbose_name='出生日期')),
                ('native', models.CharField(max_length=30, verbose_name='民族')),
                ('classNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core_app.ClassInfo', verbose_name='所属班级')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseNo', core_app.models.MyCharField(max_length=10, primary_key=True, serialize=False, verbose_name='课程号')),
                ('courseName', models.CharField(max_length=30, verbose_name='课程名')),
                ('creditHour', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='课程名')),
                ('courseHour', models.SmallIntegerField(verbose_name='课时数')),
                ('priorCourse', models.CharField(max_length=30, verbose_name='先修课程')),
                ('students', models.ManyToManyField(related_name='courses', to='core_app.StudentInfo', verbose_name='上课学生')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', core_app.models.MyCharField(max_length=10, verbose_name='开课学期')),
                ('score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='成绩')),
                ('courseNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.CourseInfo', verbose_name='课程号')),
                ('studentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.StudentInfo', verbose_name='学号')),
            ],
            options={
                'unique_together': {('studentNo', 'courseNo')},
            },
        ),
    ]
