# Generated by Django 2.2.7 on 2020-03-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinfo',
            name='courseNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core_app.CourseInfo', verbose_name='课程号'),
        ),
        migrations.AlterField(
            model_name='scoreinfo',
            name='studentNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core_app.StudentInfo', verbose_name='学号'),
        ),
    ]
